<a href="https://colab.research.google.com/github/Saleh7127/pytorch-practice/blob/main/pytorch_starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import torch
import numpy as np

In [3]:
myt = torch.arange(10)
myt

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
myt = myt.reshape(2,5)
myt

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
myt2 = torch.arange(12)

In [16]:
myt2 = myt2.reshape(-1,3)
myt2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [19]:
myt3 = torch.arange(12)

In [22]:
myt3 = myt3.view(2,6)
myt3

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [23]:
myt4 = torch.arange(12)
myt4

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
myt4 = myt4.reshape(3,4)
myt4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [27]:
myt4[1]= 100
myt4

tensor([[  0,   1,   2,   3],
        [100, 100, 100, 100],
        [  8,   9,  10,  11]])

In [28]:
myt4[1][2]= 102
myt4

tensor([[  0,   1,   2,   3],
        [100, 100, 102, 100],
        [  8,   9,  10,  11]])

In [29]:
myt5 = torch.arange(10)
myt5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
myt5[7]

tensor(7)

In [31]:
myt6 = myt5.reshape(5,2)
myt6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [32]:
myt6[:,1]

tensor([1, 3, 5, 7, 9])

In [33]:
myt6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [40]:
ta = torch.tensor([1,2,3,4])
tb = torch.tensor([5,6,7,8])

In [41]:
# Addition

ta + tb

tensor([ 6,  8, 10, 12])

In [42]:
torch.add(ta,tb)

tensor([ 6,  8, 10, 12])

In [43]:
# Subtract
ta - tb

tensor([-4, -4, -4, -4])

In [45]:
torch.sub(ta,tb)

tensor([-4, -4, -4, -4])

In [46]:
# Multi
ta * tb

tensor([ 5, 12, 21, 32])

In [47]:
torch.mul(ta,tb)

tensor([ 5, 12, 21, 32])

In [48]:
#Div
tb/ta

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [49]:
torch.div(tb,ta)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [50]:
# Remainder
tb % ta

tensor([0, 0, 1, 0])

In [52]:
torch.remainder(tb,ta)

tensor([0, 0, 1, 0])

In [53]:
# Power/Expo
torch.pow(ta,tb)

tensor([    1,    64,  2187, 65536])

In [54]:
ta.add(tb)

tensor([ 6,  8, 10, 12])

In [56]:
ta

tensor([1, 2, 3, 4])

In [57]:
#ta = ta + tb
ta.add_(tb)

tensor([ 6,  8, 10, 12])

In [58]:
ta

tensor([ 6,  8, 10, 12])

In [59]:
ta.mul_(tb)

tensor([30, 48, 70, 96])

In [61]:
ta.sub_(tb)

tensor([25, 42, 63, 88])